port = 8443
cert = "ssl.crt"
key = "ssl.key"
cors = ["https://192.168.0.5"]

[[routes]]
method = "GET"
path = "/zebra"

[[routes.requests]]
name = "rawprinter"
method = "POST"
url = "http://localhost:8001"
body = "{{vars.data}}"

[routes.response]
body = """{{vars.callback}} ({%
  if data.rawprinter.status == 200
%}{
  Errno: 0,
  Error: ''
}{% else %}{
  Errno: 1,
  Error: 'Erro ao imprimir código de barras!'
}{% endif %})"""
headers = { Content-Type = "text/javascript" }

[[routes]]
method = "GET"
path = "/toledo"

[[routes.requests]]
name = "toledo"
method = "GET"
url = "http://localhost:8002"

[routes.response]
body = """{{vars.callback}} ({%
  if data.toledo.status == 200
%}{
  Errno: 0,
  Error: '',
  Peso: {{data.toledo.json.weight}}
}{% else %}{
  Errno: 2,
  Error: '{{data.toledo.body}}',
  Peso: 0
}{% endif %})"""
headers = { Content-Type = "text/javascript" }
